spring.application.name=media-sequencer

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/media_sequencer
spring.datasource.username=postgres
spring.datasource.password=Password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true